#server.port=8001
#spring.cloud.config.server.git.uri= "https://github.com/nexx01/ConfigData"
#spring.cloud.config.server.git.default-label=main

spring:
  application:
    name: spring-eureka-client-sentence
server:
  port: 8021

subject:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000

#eureka.client.service-url.defaultZone=http://localhost:8010/eureka/


